# Generated by Django 3.2.3 on 2021-11-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='click',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
